# Generated by Django 2.2.4 on 2019-08-31 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.Message')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reply', to='chat.Message')),
            ],
            bases=('chat.message',),
        ),
    ]
