# Generated by Django 2.2.4 on 2019-08-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.IntegerField()),
                ('mean_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bans',
        ),
        migrations.AddField(
            model_name='ban',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MGA.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='MGA.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='xlat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ylat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(default=None, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.BigIntegerField()),
                ('telephone', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('forbiddens', models.TextField()),
                ('rate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_rate', to='MGA.Rate')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_rate', to='MGA.Rate'),
        ),
    ]
