# Generated by Django 2.2.4 on 2019-08-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
