# Generated by Django 2.2.4 on 2019-08-31 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushy', '0005_auto_20160226_1946'),
        ('MGA', '0002_auto_20190826_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_device',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to='pushy.Device'),
        ),
    ]
